name: Build and Install

on:
  workflow_dispatch:

jobs:
  build_universal-barebone:
    strategy:
      matrix:
        include:
          - device: ['pinetab2', 'pinetab']
          - ui: ['barebone', 'plasma_desktop']
    runs-on: ubuntu-latest #${{ matrix.platform }#}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Install tools
      #  if#: matrix.platform == #'self-hosted'
      #  run: |
      #    sudo pacman -Syu --noconfirm
      #    sudo pacman -S --noconfirm devtools \
      #      lsof \
      #      wget \
      #      fdisk \
      #      bsdtar
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y lsof wget util-linux libarchive-tools e2fsprogs dosfstools arch-install-scripts fdisk qemu-user-static
      - name: Run build script
        run: |
          chmod +x ./build.sh
          sudo ./build.sh -u barebone -d pinetab2 -a aarch64
      - name: Compress Image
        run: |
          mv build/*.img ./archlinux-${{ matrix.device }}-${{ matrix.ui }}.img
          xz z -9 ./archlinux-${{ matrix.device }}-${{ matrix.ui }}.img
      - name: Upload Image
        uses: actions/upload-artifact@v2
        with:
          name: Compressed Image
          path: archlinux-${{ matrix.device }}-${{ matrix.ui }}.img.xz