name: Build and Install

on:
  workflow_dispatch:

jobs:
  build_universal-barebone:
    runs-on: ubuntu-latest #${{ matrix.platform }#}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      #- name: Install tools
      #  if#: matrix.platform == #'self-hosted'
      #  run: |
      #    sudo pacman -Syu --noconfirm
      #    sudo pacman -S --noconfirm devtools \
      #      lsof \
      #      wget \
      #      fdisk \
      #      bsdtar
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y lsof wget util-linux libarchive-tools e2fsprogs dosfstools arch-install-scripts fdisk qemu-user-static
      - name: Run build script
        run: |
          chmod +x ./build.sh
          sudo ./build.sh -u plasma_desktop -d pinetab2 -a aarch64 -n alarm -p 123456
